namespace GlobalConstants
{
    public static class Delays
    {
        public const int LOG_REPEAT_ERROR = 60000*5,
            RECENT_MESSAGES_SECONDS_BETWEEN_FLUSHES = 30,
            SLEEP_PERIOD_FLUSH_LOOPER_SECONDS = 3,
            PROCESSOR_METRICS_MIN_DELAY_UPDATE_LATEST_MILLISECONDS = 10000,
            PROCESSOR_METRICS_DELAY_TOTAL_PROCESSOR_TIME_MILLISECONDS=5000,
            MAX_SUB_DELAY_MILLISECONDS=2000,
            MIN_TIME_MILLISECONDS_BEFORE_MUTIMEDIA_DELETE_FILE_FROM_SCHEDULED = 65*60*1000;
    }
}