namespace GlobalConstants
{
    public static class Threading
    {
        public const int MAX_N_THREADS_SEND_MESSAGE_TO_CORE_SERVERS_FOR_USER = 10,
            MAX_N_THREADS_GET_USER_PROFILE_SUMMARYS_WHICH_ARE_LOCAL = 5,
            MAX_N_THREADS_GET_USER_PROFILE_SUMMARYS_THREAD_FOR_EACH_NODE=10,
            MAX_N_THREADS_SEND_MESSAGE_AS_CORE_SERVER_FOR_USERS=10,
            MAX_N_THREADS_SEND_MESSAGE_TO_USERS_DEVICES=10,
            MAX_N_THREADS_SEND_MESSAGE_TO_USERS_DEVICES_HERE=10,
            MAX_N_THREADS_DISTRIBUTE_FREQUENTLY_ACCESSED_USER_PROFILE_UPDATE=3,
            MAX_N_THREADS_SUCCESSFULLY_PROCESSED_MULTIMEDIA_LOCAL_ENDPOINTS_SEND=10,
            MAX_N_THREADS_QUAD_TREE_GET_IDS = 10,
            MAX_N_THREADS_QUAD_TREE_DELETE = 10,
            MAX_N_THREADS_QUAD_TREE_SET = 10,
            MAX_N_THREADS_GET_ROOM_SNAPSHOTS=10,
            MAX_N_THREADS_HASH_TAGS=10,
            MAX_N_THREADS_MULTIMEDIA_ITEMS_DELETE_PARALLEL_OPERATION = 10;
    }
}