namespace GlobalConstants
{
    public static class Timeouts
    {
        public const int GET_USER_PROFILE_SUMMARYS_INTERSERVER = 10000,
            TIMEOUT_REMOTE_DOUBLE_LOCK_OPERATION = 10000,
            TIMEOUT_REMOTE_LOCKING_OPERATION = 10000,
            TIMEOUT_FILES_RELAY_REMOTE_OPERATION = 4000,
            CLIENT_TO_CLIENT_TIMEOUT_INACTIVITY_MILLISECONDS = 5 * 60 * 1000,
            CACHED_INDEX_HTML_EXPIRES_AFTER_MILLISECONDS = 1000 * 60 * 15,
            TURN_SERVER_CREDENTIALS_TIMEOUT = 3600 * 24,
            CLIENT_ENDPOINT_TIMEOUT_HANDLER_INTERVAL_DO_TIMEOUTS_MILLISECONDS =  60 * 1000;
        [ExportToJavaScript]
        public const int TRANSFER_SERVER_BRIDGES_MANAGER_INTERVAL_DO_TIMEOUTS_MILLISECONDS = 60 * 1000;
        public const int TIMEOUT_TRANSFER_SERVER_REMOTE_OPERATION = 3000,
            GET_MACHINE_METRICSS_FOR_TRANSFER_SERVER = 2000,
            PICK_MOST_APPROPRIATE_TRANSFER_SERVERS = 3000,
            ESCAPE_WEBVIEW_BLOCKING_STREAM_TIMEOUT_MIN_MILLISECONDS = 15000,
            FILES_RELAY_ALLOW_CLIENT_RECONNECT_WITH_EXISTING_TOKENS = 1800000,//HALF HOUR
            SEND_NEW_NODE_ID_RANGE_TO_A_ASSOCIATED_NODE = 5000;
    }
}