namespace Chat
{
    public static class InterserverMessageTypes
    {
        public const string
            ChatFetchIndividualMessages="cfim",
            ChatGetAdministrators = "cga",
            ChatSetAdministrator = "csa",
            ChatRemoveAdministrator = "cra",
            ClientMessage = "cm",
            ChatLeaveRoom = "clr",
            ChatRemoveUserFromRoom = "crufr",
            ChatRoomInvite = "cri",
            ChatRemoveInviteFromRoom = "crifr",
            ChatCancelRoomInvite = "ccri",
            ChatRejectRoomInvite = "creri",
            ChatAcceptRoomInvite = "cacri",
            ChatAddReceivedInvite = "cari",
            ChatRemoveReceivedInvite = "crri",
            ChatGetMyReceivedInvites = "cgmri",
            ChatAddSentInvite = "casi",
            ChatRemoveSentInvite = "crsi",
            ChatGetMySentInvites = "cgmsi",
            ChatGetMostActiveRooms = "cgmar",
            ChatGetConversation = "cgc",
            ChatGetPmConversation = "cgp",
            ChatSendMessageAsCoreServerForUsers = "csmc",
            ChatSendMessageToUsersDevices = "csmu",
            ChatLoadMessagesHistory = "clmh",
            ChatLoadMessagesHistoryBySentAt = "clmhb",
            ChatMessageReaction = "cmr",
            ChatModifyMessage = "cmm",
            ChatDeleteMessages = "cdm",
            ChatReactToMessage = "crtm",
            ChatUnreactToMessage = "cutm",
            ChatGetUserRooms = "cgr",
            ChatModifyUserRooms = "cmur",
            ChatGetRoomSummarys = "cgrs",
            ChatMostActiveRooms="cmac",
            ChatGetMostActiveRoomsFromManager = "cmacfm",
            ChatMultimediaUpload = "cmu",
            ChatCreateRoom = "ccr",
            ChatUpdatePendingUserMultimediaItemStatus = "cupumis",
            ChatGetWallConversation = "cgwc",
            ChatGetWallCommentsConversation="cgwcc",
            ChatRemoveUserFromActiveConversations = "crufac",
            ChatSetSeenMessage = "cssm";
    } 
}